# remove_stale_folders.ps1 - untrack logs/ and models/ from the repo
# These are runtime-only directories: logs/ is generated at runtime,
# models/ holds downloaded GGUFs (already gitignored individually).
# Run from PowerShell:   powershell -ExecutionPolicy Bypass -File .\remove_stale_folders.ps1

$ErrorActionPreference = "Continue"
Set-Location -Path $PSScriptRoot

Write-Host ""
Write-Host "=== Removing stale folders from repo ===" -ForegroundColor Cyan
Write-Host ""

# Clean stale lockfile if present
if (Test-Path ".git\index.lock") {
    $gitProc = Get-Process git -ErrorAction SilentlyContinue
    if ($gitProc) {
        Write-Host "git is running. Close other git processes and rerun." -ForegroundColor Red
        exit 1
    }
    Remove-Item ".git\index.lock" -Force
    Write-Host "Cleared stale .git\index.lock" -ForegroundColor Yellow
}

# 1. Untrack the folders (keeps local copies intact)
Write-Host "Untracking logs/ ..." -ForegroundColor Cyan
git rm -r --cached logs 2>&1 | ForEach-Object { Write-Host "  $_" }

Write-Host "Untracking models/ ..." -ForegroundColor Cyan
git rm -r --cached models 2>&1 | ForEach-Object { Write-Host "  $_" }

# 2. Make sure .gitignore covers them fully going forward
$gi = Get-Content .gitignore -Raw
$additions = @()
if ($gi -notmatch "(?m)^logs/\s*$") { $additions += "logs/" }
if ($gi -notmatch "(?m)^models/\s*$") { $additions += "models/" }
if ($additions.Count -gt 0) {
    Write-Host ""
    Write-Host "Adding to .gitignore: $($additions -join ', ')" -ForegroundColor Cyan
    Add-Content .gitignore ""
    Add-Content .gitignore "# Runtime-only directories"
    $additions | ForEach-Object { Add-Content .gitignore $_ }
    git add .gitignore
}

# 3. Show what's about to be committed
Write-Host ""
Write-Host "=== About to commit ===" -ForegroundColor Cyan
git status --short

Write-Host ""
$confirm = Read-Host "Commit and push the removal? (y/N)"
if ($confirm -ne "y" -and $confirm -ne "Y") {
    Write-Host "Aborted. Index changes are still staged - run 'git reset' to undo." -ForegroundColor Yellow
    exit 0
}

# 4. Commit
$ErrorActionPreference = "Stop"
$msgLines = @(
    "chore: remove stale logs/ and models/ from repo",
    "",
    "These are runtime-only directories. logs/ is generated by the app,",
    "models/ holds downloaded GGUF files (download_model.bat creates it",
    "and the .gguf files are already gitignored individually).",
    "Both are now ignored at the directory level."
)
$msg = $msgLines -join "`n"

Write-Host ""
Write-Host "Committing..." -ForegroundColor Cyan
git commit -m $msg

Write-Host ""
Write-Host "Pushing..." -ForegroundColor Cyan
git push origin main

Write-Host ""
Write-Host "Done. Refresh https://github.com/duckcoop/omnigab to confirm." -ForegroundColor Green
